name: cba
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      run: echo "It's my uid 20015"
